apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:MOBDF43Vh48kCRdVeyHl9aUas/OOmFuNlIbKjpsTR6azbq1YLAK79nR8Q8kImBDXpX+5zG80nLSCtiL462fXlg==,iv:8QF239+IcitIUnK81xxeTV/axFTV3k4AsxIOInc/7fI=,tag:GkDKybZgnjQQRa/xh1KIIA==,type:str]
sops:
    age:
        - recipient: age1d36v9zvqg5fraumcpg470etkjtztyz0fw8dgj5v5pmd9mr0t29zq3gzkhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWkxwNUk3d0Y3aTdYbXdJ
            SzQ4bzlCanpDUWFxZ2MxN0pQQ012b0pFY1U0CndXQ0YyZlJMcUNaR2hQMzNsOHlU
            dm5SdzRVVFBkTHcvUXpudHgzSmFxcXcKLS0tIEU0THlzdkFlNWhxNFZrTFZnQzdF
            eUNPcWZhWmFMN1ZEZ1NSeUNaUlF4MmsK++EaWeEaRw8HkYEnNkmONwzX21791eXu
            9J1yGOwPpiFXPL8i5meYdU83dNkGlHg5mhV0I+Z8bZTzKTBm20qCiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T09:18:23Z"
    mac: ENC[AES256_GCM,data:c+7g47NqxM5m+GyhD6aQqtm+9DG0y8jksk4NttyYbratYSCiyN+pvLouHEYW2c4R/n7aEw9RAWLDymUuxKUdHmJmS13u4r1w+PqIUom2vARpVpHJ9aNY4pr4D/bKkSpZiJdaQY0FxYTLU1boNYNx/8Smu6ZVBefYDYgTjj6Vd2Y=,iv:JFObZuzTq8/V+gL0rCpoKZjaMBuqWiRu0yiYec3V6cc=,tag:vVSAH6uPKx4lIQBGFXsg6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
