apiVersion: v1
kind: Secret
metadata:
    name: backup-store
    namespace: ferrisbot
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:WibTNMULq3cTaKfr/YyIMQ4IMEs=,iv:WTK19x7wfK5QJnQFxgwz12u8GvL5JeT8KrFNnvXes54=,tag:3SyXyhumTAz2mASuAQ1dEw==,type:str]
    secret-key: ENC[AES256_GCM,data:37CoqHBUDXwQCV8VErTKk6QXRV671WCZgHXpFTJp+qMgUOBSaHpMiw==,iv:p4WuVojPnjXvgy6LCC+9VBv7877OETFwyNu0UnY5TYU=,tag:8VQfEtkX76kIYyH/rAC+Wg==,type:str]
sops:
    age:
        - recipient: age1d36v9zvqg5fraumcpg470etkjtztyz0fw8dgj5v5pmd9mr0t29zq3gzkhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMUtlTFhXdUkvcjlkZVc0
            VSszVGRWRzAxUG9XbnU3Njh1Vk9xSzByM0V3CnE5TkRROW5iUExGem9PQkFyVWdv
            UmtzLzVlUy84WmNBVGFUQTZ0SUN4Q0UKLS0tIFZWUHk1YUlBQUxqZTl2Y0tvWGlq
            UmpXN2RvclczVWMxa2NKTTVxMnhnKzgKc8gAvff9qqJOqHnZOQ8TUFJ/gXK0LxGf
            RmoTkp9xhL2EUZrbd8X+nkLqMjRD3Ud3jn6+zT0VPES+49qPQQ0xxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T08:28:53Z"
    mac: ENC[AES256_GCM,data:+aAU5k9DXcCuiKCrf8/M6jdaiPv4lZbrTNFgamyBx2WIzrdXaU/1M6MnHed2BRm6pBeeMKYhGPLzCeSBJKk8Edg9ZMom8We3qJloJUY1v91R6UDCNQ174nS3AJ/L7SpHyuQ3zrmfW/hw2DTRyTLVlym7T7BITxUrpC3NevS1Xbw=,iv:q3Ic39Zi0EUmMqFpNtwBOJI5E8mZ9bE5q07jnSokx/g=,tag:0KV9kyPqfwCjMDhNPEGubw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
