apiVersion: v1
kind: Secret
metadata:
    name: ferrisbot
    namespace: ferrisbot
type: Opaque
stringData:
    discord-token: ENC[AES256_GCM,data:OkGi8QR31V68EE3ZZmPa4pB4lewSeCBrUcianbberTr4evYA1+KAL2aHfXQDBZWKlSbpP3sTYcI+6+tgHyQ1kGVvJDht7w==,iv:X+2IpEuvAfyo4tsiHgfrw9hyREcCxntxQjC0YVXkzNE=,tag:OCADm+0NjOC413RekVNq6A==,type:str]
sops:
    age:
        - recipient: age1d36v9zvqg5fraumcpg470etkjtztyz0fw8dgj5v5pmd9mr0t29zq3gzkhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSEc5Z3doOEoyV09LcjVz
            VUk4aVB5Uk1DQit5TUErT0JGbENPQ0N0WlhzCjlSZW5OVis0Z0hOeFFja3N5RDFK
            MEV3WFVLU3ZjM3VPUjhqdE15L3pHa0kKLS0tIFpjczNRZUhod3oxZ05td0ZVRE9Z
            em85eDNVdG9rZGZkcnhvcjhUdTc0NnMKiw51f5B3Q9B+QbZO0ESV62ur7+NE12dL
            zycu3X3zUEl2OXI7dEsRIu3sJUn9gQEPUo5btrL82EKjJCP7f3w2Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T20:58:55Z"
    mac: ENC[AES256_GCM,data:us5524u0A3Srk9/4AjYED7e10mj4KunKH/Eqrw92fJo3CxFRrAKqJRYyIl6vrsADha32tfkOSO8S3MhZoHpIlBi8gctErPMqeSMybOAOjdopQ6hplUtfyOHFIogoAXnRH8j2yoS9cHSxd3mCJ6XUKr9L5PxWrOUchp0fzlZPKbk=,iv:MLfFy8C/GraVAkaL6H0GyQ8uSGZcuCxE3GCx68js6MQ=,tag:+kIpopl1CVyxFZiZ5Kcq/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
