apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: ferrisbot
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:XCpSx4ym7K9X3f99r4xNpI+hvBR+wFTPUFwKdpSkO9XHCWIbBCSp4OpYRPldmh0ki1ORib+9JzxxMenoh9DsKGo5p+g10ev+l/xvetWAIQOQreM3sZynDST69A9uHW5AZw1usdxOoPtT/CKi+8w5G7p13cDoKdjN2CpMB33dE4CKTZBtfNr66Qbg4rjMqm+TQwB3EwQzmwASzalPSZGa8Wa9eVjt0xDXqzQE0AssGWs5E3a2GbEzZc2Re92o1DJMYov0W4XezdP6fB0OdGkNkRqV/Tj8VUtQM8nF8bpf+RSayQOor7scMTnUCTk=,iv:gCx+C2t7hq+JJtW47idKt2ty8Dbr3Pb54gIXfAVbS08=,tag:Pm3xDOZXP50XQMjv04nTyw==,type:str]
sops:
    age:
        - recipient: age1d36v9zvqg5fraumcpg470etkjtztyz0fw8dgj5v5pmd9mr0t29zq3gzkhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dkNUMVFNbFZoVEVSbWFl
            b29vQ21KbnFXK3FZV0NEWFZSblRudUtqN1g4CjJWRk9JaCs5cVZjN1JReUxUZjF3
            UldZaDNxT2NRZUtYZ0ZydHhtT1h6YzQKLS0tIE9OdGJXcjhhdEEwS3BTZzgxZ00r
            U01SVlNReWZJVVRDdWoySGFqMW9LL1UKt0xeGuxfYIjNKbBRMpZrrRrLAhmZzk/k
            XGhERzH9eXS8FBGjDLPTEcuziFQlaMO/269Tz3BGTuxMw14HVWZT+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T21:43:56Z"
    mac: ENC[AES256_GCM,data:HIsgwABZiKEj86EKLCmg/4fV2t5ssrmgzv1zzmIe7dT3nrJc4MhaBuhDoicYnJN0urcoF37LIUcgwMtGrvL0Zo19dT8lfSInnS0HijQ+zCnt8hMGYx1SwLXGpWeJFrUKvszCePQn81bXelwI7Pjve2INg2bM4t2XJRJnX750eRA=,iv:9JjMgjoYfIjBIoU4ApC78XFtnLVa1ZBNyBMEFIqWb1w=,tag:nN64aQhrXkTZLHq4lr5eEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
